Vagrant.configure("2") do |config|
    config.vm.box = "precise64"
    config.vm.box_url = "http://files.vagrantup.com/precise64.box"

    config.vm.network :private_network, ip: "192.168.56.12"
        config.ssh.forward_agent = true

    config.vm.provider :virtualbox do |v|
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--memory", 512]
        v.customize ["modifyvm", :id, "--name", "scala-box"]
    end

    config.vm.synced_folder "../", "/project_root", :nfs => true

    # config.vm.provision :puppet do |puppet|
    #     puppet.manifests_path = "puppet/manifests"
    #     puppet.manifest_file = "default.pp"
    #     puppet.module_path = "puppet/modules"
    #     puppet.options = ['--verbose']
    # end
end
